Ml il8n the specs
sparc-request/sparc-request pull request #1862
Opened 2019-05-23 13:24 UTC by marklohr

https://www.pivotaltracker.com/story/show/157261689

If an institution wants to use SPARC in a language other than English, Feature specs will not pass because we have hard-coded English statements. Any time a spec interacts with an element on the page, it needs to use the i18n.t(...) format, rather than the text as a string to ensure it is safe for internationalization.

Task: Find all instances where text is hard-coded in feature specs and replace them with the corresponding i18n sequences.

2019-05-23 17:20 UTC, kayla-glick requested changes
This story shouldn't be adding any new YAML unless there are raw strings being used in the application that need to be YAMLized. I pointed out several cases where YAML was added but should instead be referencing an existing key based on how it's used in the application, but did not highlight all of them as it would take too long to do so.

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/en.yml
> +    save_continue: "Save and Continue"
This value is pulled from `t(:proper)[:navigation][:bottom][:save_and_continue]` in the application

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/service_requests/navigation/_footer.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/en.yml
> +    edit_study: "Edit Study Information"
This should be using the `edit` key above and passed a `protocol_type` parameter

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/dashboard.en.yml
> +        view_study_details: "View Study Details"
This value is pulled from `t('protocols.view_details.button')` in the application and needs a `protocol_type` parameter.

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/protocols/_summary.html.haml
https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/dashboard/protocols/_summary.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +        view_study_details: "View Study Details"
This value is pulled from `t('protocols.view_details.button')` in the application and needs a `protocol_type` parameter.

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/protocols/_summary.html.haml
https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/dashboard/protocols/_summary.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +        submit_request: "Submit Request"
This value is pulled from the above `submit` key

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/service_requests/navigation/_footer.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +      short_interaction: "Short Interaction"
This value is pulled from `t(:proper)[:right_navigation][:short_interaction][:header]` in the application

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/service_requests/right_navigation/_right_navigation.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +      help: "Help/FAQs"
This value is pulled from `t(:proper)[:right_navigation][:faqs][:header]` in the application

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/helpers/service_requests_helper.rb

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +      contact: "Contact Us"
This value is pulled from `t(:proper)[:right_navigation][:contact][:header]`

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/service_requests/right_navigation/_right_navigation.html.haml

2019-05-23 17:20 UTC, kyle-glick commented on config/locales/proper.en.yml
> +      new_research_study: "New Research Study"
This value is pulled from `t(:protocols)[:studies][:new]` in the application

https://github.com/sparc-request/sparc-request/blob/v3.5.0/app/views/service_requests/protocol/_protocol_display.html.haml

2022-08-30 14:59 UTC, amcates commented
@jleonardw9 @Stuart-Johnson I believe this pull request should just be trashed.  It's really old and I think we have moved past this.  Thoughts?

2022-08-30 15:05 UTC, Stuart-Johnson commented
@amcates Agreed

2022-08-30 15:08 UTC, closed without merging